### ISSUE TITLE
Handbook link broken 

### ISSUE THREAD

**Issue by janimo** [cryptoparty/handbook#126]
The first link in the readme is broken, should probably point to https://www.cryptoparty.in/learn/handbook

**Comment by samthetechie** [comment]
On 25/01/16 19:19, Jani Monoses wrote:
> The first link in the readme is broken, should probably point to
> https://www.cryptoparty.in/learn/handbook
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cryptoparty/handbook/issues/126>.
> 
thanks jani, fixed.

samthetechie

-- 
Samuel "samthetechie" Carlisle
https://samthetechie.github.io/
BEng (Hons) Dunelm MIET
PGP Public Key: 54828CAA
9E01 D8A4 CFEB ED72 B0D2
70D7 1D57 A297 5482 8CAA
