### ISSUE TITLE
Cryptocat is an inactive project

### ISSUE THREAD

**Issue by elationfoundation** [cryptoparty/handbook#128]
Cryptocat is [listed as an encrypted messaging application](https://github.com/cryptoparty/handbook/blob/master/src/chapter_12_instant_messaging_encryption/00_setting_up_encrypted_messaging.md#all-os---cryptocat)  This tool has been [shut down by its creator](http://web.archive.org/web/20160222145547/https://crypto.cat/) while he developed a new version. This section should be updated to either mention that it is currently offline or should have the cryptocat portion removed.

**Comment by PeterTonoli** [comment]
Cryptocat is back, and service has resumed according to @cryptocatapp "Cryptocat service has resumed. Download the new Beta client" on March 30. Suggest we close this issue?

**Comment by tonghuix** [comment]
https://crypto.cat/ still not work

**Comment by yuvadm** [comment]
It's back in beta indeed. Closing.
